default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: 'v9.16.0'
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: name-tests-test
      args:
        - --pytest
      exclude: ^tests/factories|^tests/types|^tests/utils|^tests/test_types
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: local
    hooks:
        - id: mypy
          name: mypy
          entry: pdm run mypy
          require_serial: true
          language: system
          types: [ python ]
